# Generated by Django 4.0.5 on 2022-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('course', models.DateField(default='2022-06-29')),
            ],
            options={
                'ordering': ['dish_title'],
            },
        ),
    ]
